### ISSUE TITLE
sudden high battery drain.

### ISSUE THREAD

**Issue by CameronD73** [vmware/herald-for-ios#130]
The household has 2 iphones:

1. 6s running iOS 14.4   battery health: 50%
2. 6 running iOS 12.5.1  battery health: 90%

On Mon 15th Feb the 6s went flat overnight for the first time I can remember and then again on the following night.

Checking battery usage graphs _on both phones_ showed rapid steady battery decrease overnight and the CPU running at 100% in screen-off mode.  With the phones' limited logging it is hard to say for certain, but the 10-day plot shows a definite change in background rates starting on Monday.  Overnight the battery usage by app lists Covidsafe as the only app running but attributes a "-" as the percentage which usually means less than 1%. My interpretation of this is that the remainder is in the kernel itself. When I disable location services for covidsafe then this disappears - when I re-enable them then the 100% cpu usage returns.

**Comment by adamfowleruk** [comment]
Please report this to the COVIDsafe team in the first instance here: https://github.com/AU-COVIDSafe/mobile-ios/issues including the version of COVIDsafe you are running (I believe they've just published another update - perhaps try that version?).

They will be able to diagnose specific issues with their app and can then come back to our team if the issue is with the Herald library. Recent Herald battery drain reports can be found on our website: https://vmware.github.io/herald/efficacy/results (Some tests are with location on, others with location off)

Thanks for the report.

**Comment by CameronD73** [comment]
Thanks, sorry for the mispost.
